icon_select_field.settings:
  type: config_object
  mapping:
    custom:
      label: 'Custom'
      type: sequence
      sequence:
        type: mapping
        mapping:
          key:
            label: 'Key'
            type: string
          display_name:
            label: 'Display Name'
            type: string
